name: projectOne
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- numpy
- pandas
- matplotlib
- pip
- pip:
- ipykernel
- requests
- census
- us
- gmaps
- ipywidgets
- xmltodict
- plotly
- cufflinks